### ISSUE TITLE
GFF Converter can't handle chromosomes with one gene

### ISSUE THREAD

**Issue by aakashsur** [CuypersBart/SL-Seq#1] opened 2017-07-23 01:00 UTC
I tried using the python script for converting the leishmania infantum gff from TriTrypDB (attached), and I ran into index out of bounds errors related to the fact that there was a contig with only one gene on it. It looks like the script checks the start/stop position of the next gene without checking if there is a next gene. I was able to get around the issue by changing lines 78 and 93 to essentially skip those cases. You should be able to replicate the issue by using the gff file. (I had to change the file extension for GitHub)
[TriTrypDB-33_LinfantumJPCM5.txt](https://github.com/CuypersBart/SL-Seq/files/1167792/TriTrypDB-33_LinfantumJPCM5.txt)

**Comment by CuypersBart** [comment] 2017-08-06 15:54
Hi aakashsur, 

thank you very much for pointing out this problem and leading me directly to the cause of the error!

Indeed, the gff files I used for testing never contained single gene contigs, and therefore this problem was never discovered by me. I have adapted to code not to throw out these cases, but handle them in the same way as other genes are handled in the new version that I have just committed to GIT.

If you have any more issues, please let me know. It is exactly because people report these types exceptions that the code can improve!

Cheers,

Bart

**Closed as completed by CuypersBart** 2017-08-06 15:54 UTC
